"""Generate ASSUMPTIONS.md from the settings in Boss.py (A3). No value is typed
by hand: the register (setting, value, basis) comes from
tools/baseline_draft.register(), and the full settings table lists every
upper-case scalar setting in Boss.py as it is at run time.

    python tools/assumptions.py
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
sys.path.insert(0, os.path.join(ROOT, 'tools'))


def main():
    import Boss
    from baseline_draft import register
    L = ['# Assumptions (generated by tools/assumptions.py; do not edit by hand)', '',
         'Basis labels: DATA (measured), LITERATURE (cited), DECISION (author), JUDGEMENT (not '
         'identifiable from data; bracketed by sensitivities in outputs/sensitivity_oat.csv).', '',
         '## Register', '', '| setting | value | basis |', '|---|---|---|']
    L += [f'| {a} | {v} | {b} |' for a, v, b in register()]
    L += ['', '## All settings in Boss.py', '', '| setting | value |', '|---|---|']
    for k in sorted(vars(Boss)):
        v = getattr(Boss, k)
        if k.isupper() and not k.startswith(('FILE_', 'COL_', 'SHEET_')) and k not in ('DATA_DIR', 'OUT_DIR', 'FIG_DIR', 'FACTORS_DIR') \
                and isinstance(v, (bool, int, float, str, tuple, type(None))):
            L.append(f'| `{k}` | `{v!r}` |')
    with open(os.path.join(ROOT, 'ASSUMPTIONS.md'), 'w') as f:
        f.write('\n'.join(L) + '\n')
    print(f'ASSUMPTIONS.md: {len(L)} lines')


if __name__ == '__main__':
    main()
