"""A1 evidence, generated: the 2026 consents nowcast under each method, the
household-size test and channel levels on 2018-2023 (both population dates),
and the join under the adopted settings. Nothing here sets a parameter.

    python tools/near_term_join.py      # -> outputs/near_term_join.md, .json
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import engine  # noqa: E402
import validation  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_MD = os.path.join(ROOT, 'outputs', 'near_term_join.md')
OUT_JSON = os.path.join(ROOT, 'outputs', 'near_term_join.json')


def main():
    B = validation.run_boss()
    import Boss
    if B['_join_mode'] == 'market_excess':
        ji, nc = B['join_info']['50th'], B['nowcast']
        res = dict(mode='market_excess', near_mode=Boss.NEAR_TERM_MODE, gap_ref_basis=Boss.NEAR_TERM_GAP_REF,
                   nowcast_method=Boss.NOWCAST_METHOD, consents_2026=nc['total'], O26=ji['O26'], R26=ji['R26'],
                   R27=ji['R27'], e26=ji['e26'], gap_ref=ji['gap_ref'], rho=ji['rho'],
                   join_2026_2050=float(ji['join'][1:].sum()), scenario=B['_scenario'])
        with open(OUT_JSON, 'w') as f:
            json.dump(res, f, indent=2)
        L = ['# Near-term market excess (generated by tools/near_term_join.py)', '',
             f"2026 consents ({Boss.NOWCAST_METHOD}, observed only): {nc['total']:,.0f}; 2026 building "
             f"= {Boss.COMPLETION_RATE:.2f} x consents = {ji['O26']:,.0f} dwellings (all categories).",
             f"Requirement 2026 {ji['R26']:,.0f} -> excess {ji['e26']:+,.0f}; requirement 2027 {ji['R27']:,.0f} "
             f"-> gap_ref {ji['gap_ref']:+,.0f} (basis {Boss.NEAR_TERM_GAP_REF}), fading at rho = {ji['rho']:.2f}.",
             f"Booked as {Boss.NEAR_TERM_MODE}: {float(ji['join'][1:].sum()):+,.0f} dwellings over 2026-2050 "
             f"(scenario {B['_scenario']})."]
        with open(OUT_MD, 'w') as f:
            f.write('\n'.join(L) + '\n')
        print('\n'.join(L))
        return
    if B['_join_mode'] != 'nowcast':
        raise SystemExit("NEAR_TERM_JOIN is neither 'market_excess' nor 'nowcast': nothing to report.")
    cm = B['consents_monthly']
    nc = {m: engine.nowcast_year(cm, 2026, m, Boss.NOWCAST_SEASONAL_YEARS)
          for m in ('seasonal_share', 'same_period_ratio', 'last_12_months')}
    ev = {}
    for d in ('march_quarter', 'census_night', 'mid_year'):
        Bd = B if d == Boss.CHANNEL_POP_DATE else validation.run_boss(CHANNEL_POP_DATE=d)
        ev[d] = Bd['excess_evidence']
    ji = B['join_info']['50th']
    ch = {k: float(v[1:].sum()) for k, v in ji['channels'].items()}
    pn = B['pop_nowcast']
    res = dict(nowcast={m: {k: v for k, v in n.items()} for m, n in nc.items()},
               method_in_use=Boss.NOWCAST_METHOD, evidence=ev, pop_date_in_use=Boss.CHANNEL_POP_DATE,
               shares_in_use=B['join_shares'], O26=ji['O26'], R26=ji['R26'], R27=ji['R27'],
               e26=ji['e26'], e27=ji['e27'], channels_2026_2050=ch, population_nowcast=pn,
               lag_w=B['lag_w'], completion=Boss.COMPLETION_RATE, scenario=B['_scenario'])
    with open(OUT_JSON, 'w') as f:
        json.dump(res, f, indent=2, default=float)

    L = ['# Near-term join (A1): evidence and result (generated by tools/near_term_join.py)', '',
         f"Scenario {B['_scenario']}; completion rate {Boss.COMPLETION_RATE:.2f}; lag W = {B['lag_w']:.3f} yr.", '',
         '## 2026 consents (all categories)', '',
         '| method | observed months | observed | estimated rest of year | 2026 total |', '|---|---|---|---|---|']
    for m, n in nc.items():
        L.append(f"| {m}{' (in use)' if m == Boss.NOWCAST_METHOD else ''} | {n['months_observed'][0]}-"
                 f"{n['months_observed'][-1]} | {n['observed']:,.0f} | {n['estimated_missing']:,.0f} | "
                 f"{n['total']:,.0f} |")
    L += ['', '## Population, 2026', '',
          (f"Observed growth, year ended June 2026: {pn['observed_growth']:,.0f} ({pn['status']}); projection "
           f"median {pn['observed_growth'] - pn['shift']:,.0f}; levels from 2026 shifted by {pn['shift']:+,.0f}."
           if pn else 'Population nowcast off.'),
          '', '## Channel evidence, census 2018 -> 2023 (ONE interval; no standard error can be formed)', '',
          '| population paired with census households | change in household size, census | Stats NZ shape | '
          'household channel | redevelopment | vacancy | households | shares R / V / H |', '|---|---|---|---|---|---|---|---|']
    for d, e in ev.items():
        lv, sh = e['levels'], e['shares']
        L.append(f"| {d}{' (in use)' if d == Boss.CHANNEL_POP_DATE else ''} | {100 * e['change_S_census']:+.2f}% | "
                 f"{100 * e['change_S_shape']:+.2f}% | {'included' if e['households_included'] else 'excluded'} | "
                 f"{lv['redevelopment']:,.0f} | {lv['vacancy']:,.0f} | {lv['households']:,.0f} | "
                 f"{sh['redevelopment']:.3f} / {sh['vacancy']:.3f} / {sh['households']:.3f} |")
    L += ['', '## Join, median path (dwellings, all categories)', '',
          f"2026: observed-implied completions {ji['O26']:,.0f} vs requirement {ji['R26']:,.0f} -> excess "
          f"{ji['e26']:+,.0f}. 2027 lagged share: {ji['e27']:+,.0f} (requirement {ji['R27']:,.0f}).", '',
          '| channel | 2026-2050 |', '|---|---|']
    for k, v in ch.items():
        L.append(f'| {k} | {v:+,.0f} |')
    L.append(f"| net join | {float(ji['join'][1:].sum()):+,.0f} |")
    with open(OUT_MD, 'w') as f:
        f.write('\n'.join(L) + '\n')
    print('\n'.join(L))


if __name__ == '__main__':
    main()
